use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::ffi::OsStr;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::mpsc;
use std::thread;

use anyhow::{Context, Result, bail};
use clap::Args;
use serde::Deserialize;
use tempfile::{Builder, NamedTempFile};
use walkdir::WalkDir;

/// Arguments controlling tracked Acton wrapper generation.
#[derive(Debug, Args)]
pub(crate) struct WrappersArgs {
    /// Verify that every tracked wrapper is current without modifying files.
    #[arg(long)]
    check: bool,

    /// Acton project manifest containing the contract registry.
    #[arg(long, default_value = "Acton.toml")]
    manifest: PathBuf,

    /// Acton executable used to build contracts and generate wrappers.
    #[arg(long, env = "ACTON_BIN", default_value = "acton")]
    acton: PathBuf,

    /// Maximum number of concurrent wrapper generator processes.
    #[arg(short = 'j', long, value_name = "N")]
    jobs: Option<usize>,
}

/// Minimal portion of Acton.toml needed to locate wrapper destinations.
#[derive(Debug, Deserialize)]
struct Manifest {
    /// Contracts keyed by their stable Acton contract IDs.
    contracts: BTreeMap<String, ManifestContract>,
}

/// Manifest fields used to resolve one tracked wrapper path.
#[derive(Debug, Deserialize)]
struct ManifestContract {
    /// Contract-specific wrapper settings introduced by Acton.
    wrappers: Option<ManifestWrappers>,
}

/// Wrapper settings from one `[contracts.<name>.wrappers]` table.
#[derive(Debug, Deserialize)]
struct ManifestWrappers {
    /// Tolk wrapper settings.
    tolk: Option<ManifestTolkWrapper>,
}

/// Tolk wrapper settings from Acton.toml.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct ManifestTolkWrapper {
    /// Directory where Acton writes this contract's generated wrapper.
    output_dir: Option<PathBuf>,
}

/// One wrapper expected from a contract registered in Acton.toml.
#[derive(Debug)]
struct WrapperTask {
    /// Stable Acton contract ID passed to `acton wrapper`.
    id: String,
    /// Repository path where the generated wrapper is tracked.
    path: PathBuf,
}

/// Generated bytes and their comparison with the tracked wrapper.
#[derive(Debug)]
struct GeneratedWrapper {
    /// Index preserving deterministic manifest order after parallel work.
    index: usize,
    /// Generated wrapper bytes.
    contents: Vec<u8>,
    /// Whether the tracked file existed and was byte-identical.
    current: bool,
}

/// Failure reported by one parallel Acton wrapper process.
#[derive(Debug)]
struct GenerationFailure {
    /// Index preserving deterministic manifest order after parallel work.
    index: usize,
    /// Process output when Acton started but returned unsuccessfully.
    output: Option<Output>,
    /// Launch or I/O error when wrapper bytes could not be produced.
    error: Option<anyhow::Error>,
}

/// Regenerate all wrappers, or fail when `--check` detects drift.
pub(crate) fn run(args: WrappersArgs) -> Result<()> {
    let root = env::current_dir().context("failed to resolve the repository root")?;
    let manifest_path = resolve(&root, &args.manifest);
    let tasks = load_tasks(&root, &manifest_path)?;

    validate_inventory(&root, &tasks)?;
    prepare_wrapper_directories(&tasks, args.check)?;
    build_contracts(&root, &manifest_path, &args.acton)?;

    let jobs = effective_jobs(args.jobs, tasks.len())?;
    eprintln!(
        "Generating {} Acton wrappers with {jobs} parallel job(s)",
        tasks.len()
    );
    let generated = generate_wrappers(&root, &manifest_path, &args.acton, &tasks, jobs)?;

    let stale = generated
        .iter()
        .filter(|wrapper| !wrapper.current)
        .map(|wrapper| wrapper.index)
        .collect::<Vec<_>>();

    if args.check {
        if !stale.is_empty() {
            let mut message = format!("{} tracked wrapper(s) are out of date", stale.len());
            for index in stale {
                let task = &tasks[index];
                let state = if task.path.is_file() {
                    "stale"
                } else {
                    "missing"
                };
                message.push_str(&format!(
                    "\n- {state}: {} ({})",
                    display_path(&root, &task.path),
                    task.id
                ));
            }
            message.push_str("\nrun `cargo xtask wrappers` to regenerate them");
            bail!(message);
        }

        eprintln!("Checked {} tracked Acton wrappers", tasks.len());
        return Ok(());
    }

    let mut updated = 0;
    for wrapper in generated {
        if wrapper.current {
            continue;
        }
        let task = &tasks[wrapper.index];
        write_atomic(&task.path, &wrapper.contents)?;
        eprintln!("Updated {}", display_path(&root, &task.path));
        updated += 1;
    }

    eprintln!(
        "Generated {} tracked Acton wrappers ({updated} updated)",
        tasks.len()
    );
    Ok(())
}

/// Parse Acton.toml and resolve exactly one configured wrapper path per contract.
fn load_tasks(root: &Path, manifest_path: &Path) -> Result<Vec<WrapperTask>> {
    let contents = fs::read_to_string(manifest_path)
        .with_context(|| format!("failed to read {}", manifest_path.display()))?;
    let manifest: Manifest = toml::from_str(&contents)
        .with_context(|| format!("failed to parse {}", manifest_path.display()))?;

    if manifest.contracts.is_empty() {
        bail!(
            "manifest contains no contracts: {}",
            manifest_path.display()
        );
    }

    let mut paths = BTreeMap::new();
    let mut tasks = Vec::with_capacity(manifest.contracts.len());
    for (id, contract) in manifest.contracts {
        let output_dir = contract
            .wrappers
            .as_ref()
            .and_then(|wrappers| wrappers.tolk.as_ref())
            .and_then(|tolk| tolk.output_dir.as_ref())
            .with_context(|| {
                format!("contract {id} must define [contracts.{id}.wrappers.tolk] output-dir")
            })?;
        let path = wrapper_path(root, output_dir, &id)?;
        if let Some(existing) = paths.insert(path.clone(), id.clone()) {
            bail!(
                "contracts {existing} and {id} resolve to the same wrapper: {}",
                display_path(root, &path)
            );
        }
        tasks.push(WrapperTask { id, path });
    }
    Ok(tasks)
}

/// Resolve `<output-dir>/<contract-id>.gen.tolk` from Acton's per-contract config.
fn wrapper_path(root: &Path, output_dir: &Path, id: &str) -> Result<PathBuf> {
    if output_dir.as_os_str().is_empty() {
        bail!("wrapper output-dir for {id} must not be empty");
    }
    Ok(resolve(root, output_dir).join(format!("{id}.gen.tolk")))
}

/// Reject wrapper files that have no corresponding contract in Acton.toml.
fn validate_inventory(root: &Path, tasks: &[WrapperTask]) -> Result<()> {
    let expected = tasks
        .iter()
        .map(|task| task.path.clone())
        .collect::<BTreeSet<_>>();
    let data_dir = root.join("data");
    let mut unexpected = Vec::new();

    for entry in WalkDir::new(&data_dir).follow_links(false) {
        let entry = entry.with_context(|| format!("failed to scan {}", data_dir.display()))?;
        if !entry.file_type().is_file()
            || entry.path().extension() != Some(OsStr::new("tolk"))
            || entry.path().parent().and_then(Path::file_name) != Some(OsStr::new("wrappers"))
            || !entry.file_name().to_string_lossy().ends_with(".gen.tolk")
        {
            continue;
        }
        if !expected.contains(entry.path()) {
            unexpected.push(entry.path().to_owned());
        }
    }

    unexpected.sort();
    if !unexpected.is_empty() {
        let mut message = format!(
            "found {} wrapper file(s) without a matching Acton.toml contract",
            unexpected.len()
        );
        for path in unexpected {
            message.push_str(&format!("\n- {}", display_path(root, &path)));
        }
        bail!(message);
    }
    Ok(())
}

/// Ensure generator temporary files can be placed beside their final wrappers.
fn prepare_wrapper_directories(tasks: &[WrapperTask], check: bool) -> Result<()> {
    for task in tasks {
        let parent = task
            .path
            .parent()
            .with_context(|| format!("wrapper path has no parent: {}", task.path.display()))?;
        if parent.is_dir() {
            continue;
        }
        if check {
            bail!(
                "wrapper directory is missing for {}: {}; run `cargo xtask wrappers`",
                task.id,
                parent.display()
            );
        }
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    Ok(())
}

/// Build the manifest once before concurrent read-only wrapper generation.
fn build_contracts(root: &Path, manifest_path: &Path, acton: &Path) -> Result<()> {
    let output = Command::new(acton)
        .arg("build")
        .arg("--manifest-path")
        .arg(manifest_path)
        .arg("--color")
        .arg("never")
        .current_dir(root)
        .env("NO_COLOR", "1")
        .output()
        .with_context(|| format!("failed to start {} build", acton.display()))?;
    if !output.status.success() {
        bail!(format_command_failure("acton build", &output));
    }
    Ok(())
}

/// Generate wrappers concurrently while returning results in manifest order.
fn generate_wrappers(
    root: &Path,
    manifest_path: &Path,
    acton: &Path,
    tasks: &[WrapperTask],
    jobs: usize,
) -> Result<Vec<GeneratedWrapper>> {
    let next_index = AtomicUsize::new(0);
    let mut results = thread::scope(|scope| {
        let (sender, receiver) = mpsc::channel();

        for _ in 0..jobs {
            let sender = sender.clone();
            let next_index = &next_index;
            scope.spawn(move || {
                loop {
                    let index = next_index.fetch_add(1, Ordering::Relaxed);
                    let Some(task) = tasks.get(index) else {
                        break;
                    };
                    let result = generate_wrapper(root, manifest_path, acton, index, task);
                    if sender.send(result).is_err() {
                        break;
                    }
                }
            });
        }

        drop(sender);
        receiver.into_iter().collect::<Vec<_>>()
    });

    results.sort_by_key(|result| match result {
        Ok(wrapper) => wrapper.index,
        Err(failure) => failure.index,
    });

    let mut generated = Vec::with_capacity(tasks.len());
    let mut failures = Vec::new();
    for result in results {
        match result {
            Ok(wrapper) => generated.push(wrapper),
            Err(failure) => failures.push(failure),
        }
    }
    if !failures.is_empty() {
        bail!(format_generation_failures(root, tasks, &failures));
    }
    Ok(generated)
}

/// Generate one wrapper into its tracked directory so relative imports are stable.
fn generate_wrapper(
    root: &Path,
    manifest_path: &Path,
    acton: &Path,
    index: usize,
    task: &WrapperTask,
) -> std::result::Result<GeneratedWrapper, GenerationFailure> {
    let parent = task.path.parent().expect("wrapper parent was validated");
    let temp = match Builder::new().prefix(".wrapper-check-").tempfile_in(parent) {
        Ok(temp) => temp,
        Err(error) => return Err(generation_failure(index, None, Some(error.into()))),
    };

    let output = Command::new(acton)
        .arg("wrapper")
        .arg(&task.id)
        .arg("--manifest-path")
        .arg(manifest_path)
        .arg("--output")
        .arg(temp.path())
        .arg("--color")
        .arg("never")
        .current_dir(root)
        .env("NO_COLOR", "1")
        .output();

    let output = match output {
        Ok(output) if output.status.success() => output,
        Ok(output) => return Err(generation_failure(index, Some(output), None)),
        Err(error) => return Err(generation_failure(index, None, Some(error.into()))),
    };

    let contents = fs::read(temp.path())
        .map_err(|error| generation_failure(index, Some(output), Some(error.into())))?;
    let current = fs::read(&task.path).is_ok_and(|tracked| tracked == contents);
    Ok(GeneratedWrapper {
        index,
        contents,
        current,
    })
}

/// Construct a deterministic failure value for one worker.
fn generation_failure(
    index: usize,
    output: Option<Output>,
    error: Option<anyhow::Error>,
) -> GenerationFailure {
    GenerationFailure {
        index,
        output,
        error,
    }
}

/// Format all wrapper generation failures with their contract IDs and paths.
fn format_generation_failures(
    root: &Path,
    tasks: &[WrapperTask],
    failures: &[GenerationFailure],
) -> String {
    let mut message = format!("failed to generate {} wrapper(s)", failures.len());
    for failure in failures {
        let task = &tasks[failure.index];
        message.push_str(&format!(
            "\n\n- {}\n  wrapper: {}",
            task.id,
            display_path(root, &task.path)
        ));
        if let Some(output) = &failure.output {
            message.push_str(&format!("\n  exit status: {}", output.status));
            append_output(&mut message, "stderr", &output.stderr);
            append_output(&mut message, "stdout", &output.stdout);
        }
        if let Some(error) = &failure.error {
            message.push_str(&format!("\n  error: {error:#}"));
        }
    }
    message
}

/// Format one failed prerequisite command.
fn format_command_failure(label: &str, output: &Output) -> String {
    let mut message = format!("{label} failed with {}", output.status);
    append_output(&mut message, "stderr", &output.stderr);
    append_output(&mut message, "stdout", &output.stdout);
    message
}

/// Append bounded command output to a diagnostic message.
fn append_output(message: &mut String, label: &str, output: &[u8]) {
    let value = String::from_utf8_lossy(output);
    let value = value.trim();
    if value.is_empty() {
        return;
    }

    let truncated = value.chars().take(4_000).collect::<String>();
    message.push_str(&format!("\n  {label}:\n"));
    for line in truncated.lines() {
        message.push_str("    ");
        message.push_str(line);
        message.push('\n');
    }
    if value.chars().count() > 4_000 {
        message.push_str("    ... truncated ...\n");
    }
    while message.ends_with('\n') {
        message.pop();
    }
}

/// Choose a positive worker count capped by the number of contracts.
fn effective_jobs(requested: Option<usize>, task_count: usize) -> Result<usize> {
    if requested == Some(0) {
        bail!("--jobs must be greater than zero");
    }
    let available = thread::available_parallelism()
        .map(usize::from)
        .unwrap_or(1);
    Ok(requested.unwrap_or(available).min(task_count.max(1)))
}

/// Replace one wrapper atomically after every generator process succeeds.
fn write_atomic(path: &Path, contents: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .context("wrapper output path has no parent directory")?;
    let mut temp = NamedTempFile::new_in(parent)
        .with_context(|| format!("failed to create temporary file in {}", parent.display()))?;
    temp.write_all(contents)
        .with_context(|| format!("failed to write temporary wrapper for {}", path.display()))?;
    temp.as_file_mut()
        .sync_all()
        .with_context(|| format!("failed to flush temporary wrapper for {}", path.display()))?;
    temp.persist(path)
        .map_err(|error| error.error)
        .with_context(|| format!("failed to replace {}", path.display()))?;
    Ok(())
}

/// Resolve a command-line path relative to the repository root.
fn resolve(root: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_owned()
    } else {
        root.join(path)
    }
}

/// Render a repository-relative path with portable separators.
fn display_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_wrapper_path_from_contract_output_dir() {
        let path = wrapper_path(
            Path::new("/repo"),
            Path::new("data/example/master/wrappers"),
            "ExampleMaster",
        )
        .unwrap();
        assert_eq!(
            path,
            Path::new("/repo/data/example/master/wrappers/ExampleMaster.gen.tolk")
        );
    }

    #[test]
    fn rejects_empty_wrapper_output_dir() {
        assert!(wrapper_path(Path::new("/repo"), Path::new(""), "Example").is_err());
    }

    #[test]
    fn caps_parallel_jobs_to_the_task_count() {
        assert_eq!(effective_jobs(Some(8), 3).unwrap(), 3);
        assert_eq!(effective_jobs(Some(1), 3).unwrap(), 1);
        assert!(effective_jobs(Some(0), 3).is_err());
    }
}
